### ISSUE TITLE
Your Discord Server Isn't Joinable

### ISSUE THREAD

**Issue by LazyKB** [srnyx/personal-phantoms#1]
### Expected behavior

I would be able to join

### Actual behavior

![image](https://user-images.githubusercontent.com/87291643/206059792-9a5fe591-b488-42e6-8c72-56e50bedac10.png)

### Steps to reproduce

Join the Discord using the link from your Modrinth Page

### Checks

- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

**Comment by srnyx** [comment]
Sorry, my friend's server got raided so I paused invites to be safe. Just re-enabled them so you should be able to join now!
