### ISSUE TITLE
Per-World Settings

### ISSUE THREAD

**Issue by seema84** [srnyx/personal-phantoms#4]
### What and How?

A way to exclude worlds (which have no effect on the plugin) would be nice. So that you can deactivate it on one world, but not on another and the setting on world 1 has no effect on world 2.

### Why?

It makes sense for several worlds.

### Are there alternatives?

not really

### Checks

- [X] I have used the search at least once to check if my idea has already been suggested and perhaps already implemented.

**Comment by srnyx** [comment]
So something like this in the config?
```yml
# A list of worlds where the plugin won't be enabled
worlds-blacklist:
  list:
    - "no_plugin"
    - "no_plugin2"
  
  # If true, the list of worlds above will act as a whitelist, meaning only those worlds will have the plugin enabled
  act-as-whitelist: false

**Comment by seema84** [comment]
Yes, exactly. Is it ready inside? I hadn't seen it in the wiki.

**Comment by srnyx** [comment]
> Yes, exactly. Is it ready inside? I hadn't seen it in the wiki.

No, no, it doesn't exist yet, I just wanted to make sure we were on the same page. I'll get it implemented right now!

**Comment by srnyx** [comment]
Done; here's the dev build: https://github.com/srnyx/personal-phantoms/actions/runs/6857212230
Haven't tested it at all yet, and I used a new logic for it (that I haven't used in my other projects), so I'm not sure if it'll work
If you use the dev build, let me know how it goes and if you encounter any issues!

**Comment by seema84** [comment]
I'll try it out straight away. What I also just realised, a reload command would be quite good (to apply changes in the configs).

**Comment by seema84** [comment]
> > What I've just noticed is that you don't store the values (whether phantoms are activated or deactivated) in a file at all?
> 
> The list is maintained in the `config.yml` file, which is where you have to set the values

I mean each individual player.

**Comment by srnyx** [comment]
> I mean each individual player.

Oh, you want each player to be able to toggle per-world?

**Comment by seema84** [comment]
I am sorry if I have caused some confusion. My question about where the data is stored was not related to my original question, but was meant in general. I haven't found this data anywhere (whether a player has just deactivated a phantom or not).

**Comment by srnyx** [comment]
> I am sorry if I have caused some confusion. My question about where the data is stored was not related to my original question, but was meant in general. I haven't found this data anywhere (whether a player has just deactivated a phantom or not).

Oh I see, I'd like to keep this issue related to the original then. If you have other questions about the plugin (like that), you can ask [in my Discord server](https://srnyx.com/discord).

**Comment by srnyx** [comment]
https://github.com/srnyx/personal-phantoms/commit/fb5a029f625cd1b36dbeed705647c61159b47da0
